server:
  port: 8001

spring:
  application:
    name: library-app
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update


  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: RaviRupa1629*
    driver-class-name: com.mysql.cj.jdbc.Driver
