server:
  port: 8001

spring:
  application:
    name: library-app
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update


  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: RaviRupa1629*
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    ROOT: INFO